### ISSUE TITLE
Bug when editing

### ISSUE THREAD

**Issue by virtuald** [computer-whisperer/RoboRIO-webdash#1]
```
Exception in valueChanged callback!
Traceback (most recent call last):
  File "/mnt/sdb1/virtuald/src/frc/pynetworktables/networktables2/networktablenode.py", line 157, in fireTableListeners
    listener.valueChanged(None, key, value, isNew)
  File "/mnt/sdb1/virtuald/src/frc/pynetworktables/networktables/networktable.py", line 43, in valueChanged
    self.listener(key, value, isNew)
  File "/mnt/sdb1/virtuald/src/frc/RoboRIO-webdash/webdash/networktables_controller.py", line 29, in val_listener
    set_local_value(key, value)
  File "/mnt/sdb1/virtuald/src/frc/RoboRIO-webdash/webdash/networktables_controller.py", line 65, in set_local_value
    target_table[value_key] = value
TypeError: list indices must be integers, not str
Exception in valueChanged callback!
Traceback (most recent call last):
  File "/mnt/sdb1/virtuald/src/frc/pynetworktables/networktables2/networktablenode.py", line 157, in fireTableListeners
    listener.valueChanged(None, key, value, isNew)
  File "/mnt/sdb1/virtuald/src/frc/pynetworktables/networktables/networktable.py", line 43, in valueChanged
    self.listener(key, value, isNew)
  File "/mnt/sdb1/virtuald/src/frc/RoboRIO-webdash/webdash/networktables_controller.py", line 29, in val_listener
    set_local_value(key, value)
  File "/mnt/sdb1/virtuald/src/frc/RoboRIO-webdash/webdash/networktables_controller.py", line 65, in set_local_value
    target_table[value_key] = value
TypeError: list indices must be integers, not str
```

**Comment by computer-whisperer** [comment]
What type of entry were you editing to get this error?

**Comment by virtuald** [comment]
I don't remember.
